server:
  port: 8080
  address: 127.0.0.1
#  context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
cupSize: B
age: 18
#content: "cupSize: ${cupSize}, age: ${age}"
girl:
  cupSize: B
  age: 18
