server:
  port: 8082
  address: 127.0.0.1
#  context-path: /
spring:
  datasource:
    url: jdbc:mysql://114.215.64.222:3306/test
    username: javaproject
    password: javaproject
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
cupSize: F
age: 19
#content: "cupSize: ${cupSize}, age: ${age}"
girl:
  cupSize: F
  age: 19
