server:
  port: 8888

  spring:
    application:
      name: config-server
  cloud:
    config:
      label: master
      server:
          git:
            uri: https://github.com/forezp/SpringcloudConfig/
            force-pull: true
            searchPaths: respo
            username:
            password:


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/

#https://github.com/forezp/SpringcloudConfig/blob/master/respo/config-client-dev.properties
#https://github.com/forezp/SpringcloudConfig/respo/config-client-dev.properties
#访问地址 http://localhost:8888/config-client/dev