spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      server:
          git:
            uri: https://github.com/forezp/SpringcloudConfig/
            force-pull: true
            searchPaths: respo
            username:
            password:
server:
  port: 8888


#https://github.com/forezp/SpringcloudConfig/blob/master/respo/config-client-dev.properties
#https://github.com/forezp/SpringcloudConfig/respo/config-client-dev.properties